### ISSUE TITLE
Error with Flatconfig, `Named export 'SyntaxKind' not found. The requested module 'typescript' is a CommonJS module`

### ISSUE THREAD

**Issue by ElPrudi** [un-ts/eslint-plugin-sonar#101]
I'm currently switching from the legacy format `.eslintrc.js` to `eslint.config.js` and I'm importing this plugin as an esm module. Due to how TypeScript is built, being a commonjs file, you can't use explicit named exports.

Your file uses: 

```ts
import ts__default, { SyntaxKind, TypeFlags } from 'typescript';
```

But should rather be this:

```ts
import ts__default from 'typescript';
const { SyntaxKind, TypeFlags } = ts__default
```

or this:

```ts
import ts__default, { type SyntaxKind, type TypeFlags } from 'typescript'; // type imports are removed after ts compilation
```

**Comment by JounQin** [comment]
@ElPrudi Sorry for the delay.

I think this could an issue from https://github.com/wessberg/rollup-plugin-ts

cc @wessberg

**Comment by JounQin** [comment]
Hmm... I don't quite understand, I tried to use `@rollup/plugin-commonjs`, but the output remains same, I'll fix this in another way. And this could be an issue of rollup itself.
