### ISSUE TITLE
Support `@typescript-eslint/parser` v6 in peer dependency requirements

### ISSUE THREAD

**Issue by mcmxcdev** [un-ts/eslint-plugin-sonar#103]
`typescript-eslint` v6 was released a while ago, it would be great to support it officially.

See more: https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/

Currently, this is the output on pnpm:

```
 WARN  Issues with peer dependencies found
.
└─┬ eslint-plugin-sonar 0.12.0
  └─┬ @typescript-eslint/eslint-plugin 5.62.0
    └── ✕ unmet peer @typescript-eslint/parser@^5.0.0: found 6.1.0
```

**Comment by JounQin** [comment]
Waiting for https://github.com/SonarSource/SonarJS/issues/4005
