### ISSUE TITLE
When eslint is version 7.*, errors occur when using the 0.13.1 plugin (meta is undefined)

### ISSUE THREAD

**Issue by Le45a** [un-ts/eslint-plugin-sonar#121]
I found this problem when I tried to use version 7.32 of eslint 
when used the no-unused-private-class-members rule,eslint would report an error
Details about the error message is meta is undefined because the above rules are only supported by eslint 8.1.0
Do you want to update the eslint version in peerDependencies or remove this rule temporarily?

Anyway, thank you for providing such a great plugin

**Comment by JounQin** [comment]
Please provide an online runnable reproduction.

**Comment by JounQin** [comment]
`eslint-plugin-sonar` v0.13.2 has been released with correct peer dependency.
