### ISSUE TITLE
Peer support for @typescript-eslint/eslint-plugin v7

### ISSUE THREAD

**Issue by fduser1** [un-ts/eslint-plugin-sonar#128]
Sonar plugin is preventing us from updating eslint-plugin to v7 which was released a week ago.

Announcement: https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/

Please add support. Thanks

**Comment by JounQin** [comment]
https://github.com/SonarSource/SonarJS/blob/2b5ef1be42b183894678ef3ded6a14f6f1081c4e/package.json#L82-L84

**Comment by Pewtro** [comment]
SonarJS has since been updated to v7 of `@typescript-eslint`, https://github.com/SonarSource/SonarJS/blob/master/package.json#L82-L84
