### ISSUE TITLE
Optimize use of dependencies to be UI framework-specific

### ISSUE THREAD

**Issue by mcmxcdev** [un-ts/eslint-plugin-sonar#132]
When looking at differences between `eslint-plugin-sonarjs` and `eslint-plugin-sonar`, it seems that `eslint-plugin-sonar` installs way more transitive dependencies:

```
/eslint-plugin-sonarjs@0.24.0(eslint@8.57.0):
  resolution: {integrity: sha512-87zp50mbbNrSTuoEOebdRQBPa0mdejA5UEjyuScyIw8hEpEjfWP89Qhkq5xVZfVyVSRQKZc9alVm7yRKQvvUmg==}
  engines: {node: '>=16'}
  peerDependencies:
    eslint: ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0
  dependencies:
    eslint: 8.57.0
  dev: true
```

vs

```
/eslint-plugin-sonar@0.13.2(@babel/core@7.24.0)(@typescript-eslint/parser@6.21.0)(eslint@8.57.0)(typescript@5.4.2):
  resolution: {integrity: sha512-7mZkk4/E2tGtIi3OCNCTmEWthweWzoAj9YcsxxIDI38r7q4RDusWDpsdGHPZXp/+QU8ZKkvmE11G4DtJW+k1kg==}
  engines: {node: '>=14'}
  peerDependencies:
    '@babel/core': ^7.11.0
    '@typescript-eslint/parser': ^6.0.0
    eslint: ^8.0.0
    typescript: ^4.0.0 || ^5.0.0
  dependencies:
    '@babel/core': 7.24.0
    '@babel/eslint-parser': 7.23.10(@babel/core@7.24.0)(eslint@8.57.0)
    '@eslint-community/regexpp': 4.10.0
    '@typescript-eslint/eslint-plugin': 6.21.0(@typescript-eslint/parser@6.21.0)(eslint@8.57.0)(typescript@5.4.2)
    '@typescript-eslint/parser': 6.21.0(eslint@8.57.0)(typescript@5.4.2)
    builtin-modules: 3.3.0
    bytes: 3.1.2
    eslint: 8.57.0
    eslint-plugin-jsx-a11y: 6.8.0(eslint@8.57.0)
    eslint-plugin-react: 7.34.0(eslint@8.57.0)
    eslint-plugin-react-hooks: 4.6.0(eslint@8.57.0)
    eslint-plugin-sonarjs: 0.23.0(eslint@8.57.0)
    functional-red-black-tree: 1.0.1
    jsx-ast-utils: 3.3.5
    minimatch: 9.0.3
    scslre: 0.3.0
    tmp: 0.2.3
    typescript: 5.4.2
  transitivePeerDependencies:
    - supports-color
  dev: false
```

We are using `eslint-plugin-sonar` in a SvelteKit monorepo, so we have no need for e.g. `eslint-plugin-jsx-a11y`, `eslint-plugin-react`, `eslint-plugin-react-hooks` and so on. On top of that, these dependencies have a huge amount of bloat and install useless polyfills which is well-known due to one of their maintainers' questionable stance, unfortunately.

**Comment by JounQin** [comment]
eslint-plugin-sonar and eslint-plugin-sonarjs are totally different while eslint-plugin-sonar depends on eslint-plugin-sonarjs. See also #31

**Comment by mcmxcdev** [comment]
I don't understand why this ticket got closed right away. Your comment doesn't address the dependency bloat I mentioned and the fact that non-React users have to have React-specific deps installed.

I understand that both lint plugins are different and `eslint-plugin-sonar` pulls in `eslint-plugin-sonarjs`, so I would like to keep it installed but see it optimized.

**Comment by JounQin** [comment]
Because all of the dependencies are `imported/required` at the top level.

https://unpkg.com/browse/eslint-plugin-sonar@0.13.2/lib/index.js

**Comment by mcmxcdev** [comment]
`nolyfill` is a great project, but puts the burden on every dev to clean out the polyfills from their projects rather than solving it at the core.

I really enjoy using `eslint-plugin-sonar` but most likely will have to drop it then to ensure the codebase stays modern and fast.

**Comment by JounQin** [comment]
It's your decision and that's OK.

`eslint-plugin-sona` is a downstream project based on https://github.com/SonarSource/SonarJS, so we don't control much on the source codes by the way.
