### ISSUE TITLE
TypeScript v5 support

### ISSUE THREAD

**Issue by EvgenyOrekhov** [un-ts/eslint-plugin-sonar#88]
Can't install it in projects that use TypeScript v5, getting this:

```text
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@1.0.0
npm ERR! Found: typescript@5.0.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^5.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^4.0.0" from eslint-plugin-sonar@0.11.1
npm ERR! node_modules/eslint-plugin-sonar
npm ERR!   eslint-plugin-sonar@"*" from the root project
```

**Comment by JounQin** [comment]
Maybe it's just easy to support it by extending the version range here https://github.com/un-ts/eslint-plugin-sonar/blob/main/eslint-plugin-sonar/package.json#L35

Would you like to raise a PR?

---

Although some TS v5 only feature could be unavailable.

See also https://github.com/SonarSource/SonarJS/issues/3770
